### ISSUE TITLE
Segfaults with gfortran 6/7/8 on commit 651ef49

### ISSUE THREAD

**Issue by srk** [aoterodelaroza/critic2#15]
```
                 _   _     _          ___     
                 (_) | |   (_)        |__ \    
     ___   _ __   _  | |_   _    ___     ) |   
    / __| | '__| | | | __| | |  / __|   / /    
   | (__  | |    | | | |_  | | | (__   / /_    
    \___| |_|    |_|  \__| |_|  \___| |____|   

* CRITIC2: analysis of real-space scalar fields in solids and molecules.
  (c) 1996-2015 A. Otero-de-la-Roza, A. Martin-Pendas, V. Lua~na
  Distributed under GNU GPL v.3 (see COPYING for details)
  Bugs, requests, and rants: aoterodelaroza@gmail.com 
  If you find this software useful, please cite:
  A. Otero-de-la-Roza et al., Comput. Phys. Commun. 185 (2014) 1007-1018.
  A. Otero-de-la-Roza et al., Comput. Phys. Commun. 180 (2009) 157-166.

+ critic2 (development), commit 651ef49
 compile host: Linux NOMS 4.4.0-122-generic #146-Ubuntu SMP Mon Apr 23 15:34:04 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
 compile date: Wed  6 Jun 09:26:50 BST 2018
    using f77: gfortran-6 -g -O2 
          f90: gfortran-6 -g -O2 -ffree-form -ffree-line-length-none -fopenmp
            c: gcc-6 -g -O2 -Iqhull/
      ldflags: -static
       debug?: no
 compiled dat: /opt/CCCE/critic2/share/critic2
      datadir: /opt/CCCE/critic2/share/critic2
     dic file: /opt/CCCE/critic2/share/critic2/cif_core.dic
...was found?: T


Program received signal SIGSEGV: Segmentation fault - invalid memory reference.

Backtrace for this error:
#0  0x7353f0 in ???
#1  0x734b35 in ???
#2  0x7d9adf in ???
	at /build/glibc-Cl5G7W/glibc-2.23/nptl/../sysdeps/unix/sysv/linux/x86_64/sigaction.c:0
#3  0x0 in ???
Segmentation fault (core dumped)
```

**Comment by aoterodelaroza** [comment]
Whoa, that's odd. I tried the same version and compiler, and I cannot
reproduce this problem. Can you please recompile with --enable-debug:

FC=gfortran-6 F77=gfortran-6 CC=gcc-6 ./configure --enable-debug
make clean
make

to see if the compiler can give us a backtrace? What
OS/distribution/architecture do you use?

**Comment by srk** [comment]
Ubuntu 16.04LTS x86-64
Will try what you suggested.

**Comment by aoterodelaroza** [comment]
Also, try without the -static . I dimly remember having some trouble
with it recently.

**Comment by aoterodelaroza** [comment]
Yeah, it's the -static. I could reproduce it. I wonder how this is
done with the new gfortran.

**Comment by srk** [comment]
Yup, -static is the problem here. Removed that and it works fine.

**Comment by srk** [comment]
Thanks for the speedy response!

**Comment by aoterodelaroza** [comment]
No worries! It would be nice to have the -static option, though,
because it comes in handy when you want critic2 on a system where you
cannot have gfortran-6+ (e.g. a cluster). Digging around, it seems
that this works:

FC=gfortran-6 F77=gfortran-6 CC=gcc-6 LDFLAGS='-static -Wl,--whole-archive -lpthread -Wl,--no-whole-archive' ./configure  --enable-debug

xenon:critic2$ src/critic2 
                  _   _     _          ___     
                 (_) | |   (_)        |__ \    
     ___   _ __   _  | |_   _    ___     ) |   
    / __| | '__| | | | __| | |  / __|   / /    
   | (__  | |    | | | |_  | | | (__   / /_    
    \___| |_|    |_|  \__| |_|  \___| |____|   

* CRITIC2: analysis of real-space scalar fields in solids and molecules.
  (c) 1996-2015 A. Otero-de-la-Roza, A. Martin-Pendas, V. Lua~na
  Distributed under GNU GPL v.3 (see COPYING for details)
  Bugs, requests, and rants: aoterodelaroza@gmail.com 
  If you find this software useful, please cite:
  A. Otero-de-la-Roza et al., Comput. Phys. Commun. 185 (2014) 1007-1018.
  A. Otero-de-la-Roza et al., Comput. Phys. Commun. 180 (2009) 157-166.

+ critic2 (development), commit 651ef49
 compile host: Linux xenon 4.16.0-1-amd64 #1 SMP Debian 4.16.5-1 (2018-04-29) x86_64 GNU/Linux
 compile date: Wed Jun  6 10:50:09 CEST 2018
    using f77: gfortran-6 -g -O2 
          f90: gfortran-6 -g -O2 -ffree-form -ffree-line-length-none -fopenmp -g -fcheck=all -fbounds-check -Wall -Wunused-parameter -Wno-maybe-uninitialized -ffpe-trap=invalid -fbacktrace -fdump-core -ffree-line-length-0 -cpp
            c: gcc-6 -g -O2 -g -fbounds-check -Wall -Wunused-parameter -rdynamic -Iqhull/
      ldflags: -static -Wl,--whole-archive -lpthread -Wl,--no-whole-archive -rdynamic
       debug?: yes
 compiled dat: /usr/local/share/critic2
      datadir: /home/alberto/git/critic2/dat
     dic file: /home/alberto/git/critic2/dat/cif_core.dic
...was found?: T

CRITIC2--2018/6/6, 10:50:13.219

xenon:critic2$ ldd src/critic2 
	not a dynamic executable
