### ISSUE TITLE
typnuc 3, and then the integration is done around the nuclear still

### ISSUE THREAD

**Issue by Ceasea** [aoterodelaroza/critic2#22]
hi @aoterodelaroza ,
I try to make charge integration of non nuclear basins of ELF.

in my poor opinion, the ELF value at nuclears should be CCP, so i try "TYPNUC 3" keyword after loading the ELFCAR.

"AUTO" command provides the nuclear as CCPs ( ncp is 1 and 2 in the output below).

however, when i use "YT" to do the integration, the charge density of nuclear basins are still integrated.
(Keyword noatoms is also considered, but no changes)

is this possible?

here is my input.
........................................................................................................

crystal POSCAR
load ELFCAR typnuc 3
load CHGCAR
reference 1
integrable 2
root test
auto cpeps 1
cpreport short
yt nnm wcube

here is part of the output of "AUTO" and "YT".
........................................................................................................
 Morse sum: 0
ncp   pg  type   CPname   position (cryst. coords.) 
  1    D4h (3,3 )   cage    0.00000000   0.00000000   0.00000000    
  2    D4h (3,3 )   cage    0.50000000   0.00000000   0.50000000    
  3    C4v (3,-3) nucleus   1.00000000   0.50000000   0.22172302    
  4    D2h (3,-3) nucleus   0.25000000   0.25000000   0.50000000    
  5    Cs  (3,-1)   bond    0.19167809   0.30832191   0.35675904   
  6    D4h (3,-1)   bond    1.00000000   0.50000000   0.00000000    
  7    D2h (3,-1)   bond    0.75000000   0.25000000   0.00000000   
  8    C2v (3,1 )   ring    0.00000000   0.21883710   0.50000000    
  9    C2v (3,1 )   ring    0.15552983   0.34447017   1.00000000  
 10   D4h (3,1 )   ring    0.00000000   0.00000000   0.50000000    
........................................................................................................

List of attractors integrated
 Id   cp   ncp   Name  Z   mult           Position (cryst.) 
  1    1    1      Ti   22  --    0.0000000    0.0000000    0.0000000 
  2    2    1      Ti   22  --    0.5000000    0.5000000    0.0000000 
  3    3    2      Al   13  --    0.5000000    0.0000000    0.5000000 
  4    4    2      Al   13  --    0.0000000    0.5000000    0.5000000

**Comment by aoterodelaroza** [comment]
Hi @Ceasea: sorry for the wait. The ELF value at nuclei should indeed
be a maximum but if you are using VASP you must be using
pseudopotentials/PAW datasets and so it is likely that the atomic
shell structure is gone altogether. I recommend plotting a line from
any of the nuclei towards the interstitial to see if this is the case.

AUTO is likely not going to help very much in this case because CP
localization doesn't work very well with grids, because of #7

Your best bet to find all the maxima in the system is probably the YT
keyword, which not only gives you the integral of the charge density
in the basins but also the positions of the maxima.

If you want me to take a look more in detail, I will also need the
ELFCAR, POSCAR, and CHGCAR.

**Comment by Ceasea** [comment]
the shell structure is gone as you said. The problem is caused by the pseudopotentials method i used.
Thus, we are turning to all-electron calculations.

thanks. your reply helps me a lot.
