### ISSUE TITLE
Question regarding Morse Sum

### ISSUE THREAD

**Issue by manaslkht** [aoterodelaroza/critic2#29]
Hello, 

Firstly, thank you for making this tool available for researchers. It's been of great help in my research. 

I had a question on Morse Sum and finding BCPs. According to the manual (https://aoterodelaroza.github.io/critic2/manual/cpsearch/) in the "final report" of the AUTO output if the CP list is complete the Morse Sum is 0 for crystal and 1 for Molecule. 

I am trying to find BCPs in a hybrid perovskite structure. More specifically the Hydrogen Bonding Critical Points (HBCPs).  In my case, the AUTO output the Morse sum doesn't come to 0. The output is as follows.

* Critical point list, final report (non-equivalent cps)
  Topological class (n|b|r|c): 502(502) 587(587) 524(524) 155(155) 
  Morse sum: 284

Also the HBCPs between the many of Hydrogen and Bromide pairs are missing. Is this because the Morse sum is not 0 and the list is not complete? If so, what should I be doing to get the Morse sum to 0 and have a truly complete BCP list. 

The structure I am analyzing is quite large with 323 atoms with cell parameters of 18x18x18 angstrom.  Was curious if there was any sure shot method/strategies that I can follow to obtain all the HBCPs? I tried using AUTO SEED PAIR and the number of BCPs the code identifies goes up.  But how can I be sure the CP list is truly complete and I am not missing any BCPs. If you can shed some light on this or direct me to appropriate resources it will be really useful. Please let me know if you need more information to answer my questions. 

Thank you

**Comment by mkhorton** [comment]
Disclaimer: I’m just responding as a user of Critic2, I can’t answer your question but just wanted to share some experience of my own looking at these systems.

I’ve tried Critic2 on some hybrid perovskites and also encountered issues identifying all the bond paths, I think specifically because of the large difference in density between eg the Pb atom and the H atom. In my case I was missing bond paths between the H atom and the rest of the organic molecule. “AUTO SEED PAIR” definitely helped in this case.

The crystals I was looking at were much smaller than yours however.  Depending how you’re generating your charge density, one option may be to keep your wavefunction / charge density fixed, but tell your simulation code to re-generate it on a finer grid. Critic2 does do grid interpolation but if you can get a finer grid density directly from the simulation code too that definitely helps.

Depending on your other parameters, the Morse sum may not be exactly zero if eg you’re automatically discarding critical points it they’re below a certain field value (eg vacuum like) though that’s less likely an issue here.

I’d be interested to hear what strategies you find to solve your problem!

**Comment by aoterodelaroza** [comment]
Right now what @mkhorton says is the current state of affairs regarding finding CPs from a grid in critic2, AFAIK. Namely, have your program give you a grid that is as fine as you can, discard the vacuum CPs, and hope for the best. In large or molecular-like systems, use the SEED PAIR as a replacement or in addition to the usual seeding strategy for AUTO (TRIPLET also helps sometimes, as well as adding multiple points per pair). For a system your size I have the impression you'll have to use a humongous grid, and you will run out of memory, or disk, or both. Implementing this topoms method is the current plan A for solving this problem. I'll get to it, eventually.

**Comment by mkhorton** [comment]
Just to give a ref to TopoMS: https://github.com/LLNL/TopoMS and https://doi.org/10.1002/jcc.25181 The paper made their method look very compelling, unfortunately I found the tool itself very difficult to compile so haven't been able to evaluate it myself.

**Comment by manaslkht** [comment]
@mkhorton and @aoterodelaroza Thank you for sharing your insights/suggestions. As suggested, I will try a finer grid and seed multiple points per pair to see if I can get all the bcps. If the size of my system is the issue, I will use the unit cell of the system as a test case and see if I get all the bcps. I am hoping that seeding multiple points between pairs will do the job for both unit cell and the supercell. 

@mkhorton I did come across TopoMS as one of the tools for finding BCPs, but I found the manual for critic2 easier to follow. But I haven't given TopoMS a try. I will try to compile and see if it works for me. I will let you know if any of this works. Thanks!
