### ISSUE TITLE
Compiler Check error in crystalmod

### ISSUE THREAD

**Issue by ecbrown** [aoterodelaroza/critic2#41]
While debugging the previous issue, I turned on full checking on the ifort compiler.  This was caught:

cd /home/ecbrown/src/critic2/build-intel/src && /opt/intel/oneapi/compiler/2021.1.2/linux/bin/intel64/ifort -DHAVE_READLINE -I/home/ecbrown/src/critic2/build-intel/src/cubpack -I/home/ecbrown/src/critic2/src/qhull  -O3 -check all -traceback -qopenmp   -c /home/ecbrown/src/critic2/src/crystalmod@proc.f90 -o CMakeFiles/critic2.dir/crystalmod@proc.f90.o
ifort: warning #10182: disabling optimization; runtime debug checks enabled
/home/ecbrown/src/critic2/src/crystalmod@proc.f90(2609): catastrophic error: **Internal compiler error: internal abort** Please report this error along with the circumstances in which it occurred in a Software Problem Report.  Note: File and line given may not be explicit cause of this error.
compilation aborted for /home/ecbrown/src/critic2/src/crystalmod@proc.f90 (code 1)

That line has:

x = matmul(c%atcel(j)%x-t,transpose(x0inv)) + xlat(:,i)

I wonder if ifort is getting upset by the dimensionality of arguments to matmul.

**Comment by aoterodelaroza** [comment]
Which ifort version is this?

**Comment by aoterodelaroza** [comment]
It's difficult to say with ICEs... the error may be there or it may be somewhere else. ifort is particularly bad with those because there is nothing seemingly wrong with that statement. This is also probably a regression because last I tried with the 2019 version, it compiled without problems. I'd say the best course of action is what it says on the note: report it to the intel developers.

**Comment by ecbrown** [comment]
Will do.  Thanks for the feedback.
