### ISSUE TITLE
Guix Package for Critic2: Request for Comments

### ISSUE THREAD

**Issue by ecbrown** [aoterodelaroza/critic2#44]
Hello Alberto and Critic2 Community:

I am interested in packaging libre electronic structure theory codes for GNU Guix. To that goal, I have created a Guix package recipe for Critic2 (attached):

One can test easily by adding this to your channels.scm:

```
(channel
 (name 'ecbrown-guix)
 (url "https://ericcbrown.com/git/ecbrown-guix.git")
 (introduction
  (make-channel-introduction
   "72e02daa4cf59a5e591387e299729f2509128b58"
   (openpgp-fingerprint
    "AA5F 523D FD6D 0478 8505 6A7D C1D5 F8F0 85BF 4CF3"))))
```

Then at the shell:
```
guix pull
guix install critic2
```

should give the critic2 executable.  I have tested it with:

```
critic2 benzene.cri
```
from the example_15_01 example, and things work as expected with gnuplot graphics generated.

A couple of points:"characteristic"/"features":
* 32-bit OpenBLAS build. I don't think this is an issue, but 64-bit is available if e.g. grids get large, etc.
* CMake build
* libxc, libcint included
* GUI is enabled, though it does not run at this time (needs to be debugged)

I welcome any comments you have, and I hope this proves a useful way for people to get Critic2 in many environments and contexts provided by GNU Guix.

Best regards,
Eric
[critic2.scm.txt](https://github.com/aoterodelaroza/critic2/files/6704857/critic2.scm.txt)
[libcint.scm.txt](https://github.com/aoterodelaroza/critic2/files/6704858/libcint.scm.txt)
[libxc.scm.txt](https://github.com/aoterodelaroza/critic2/files/6704859/libxc.scm.txt)

**Comment by aoterodelaroza** [comment]
Thanks for this, sounds very good! Some things:

- I don't remember the BLAS/LAPACK calls being in any
performance-critical part of the code, so I don't think it's going to
matter very much. In fact if you don't use an external library the
build system will default to compile its own version from the
`oldlibs/` directory.

- The GUI is not in a decent state, which is why it's not
documented. It's a side-project that came out of my frustration with
open-source chemistry GUIs, more than a need to give critic2 a
graphical interface. Like all hobbyist's projects, it lags because I
don't have much time to devote to it. The GUI compiles and runs on my
system, but probably it won't in anybody else's because that part of
the build system is likely a bit broken.

**Comment by ecbrown** [comment]
My pleasure, and thank you for the feedback!  I think that based on your comments, I will disable the GUI component.  This will cut down pretty significantly the amount of packages that have to be built/fetched as a side benefit.

**Comment by ecbrown** [comment]
I've got the changes made, and will close the issue.  If anyone has questions or comments, please feel free to reach out.
