### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by PolyuWeldingSpock** [aoterodelaroza/critic2#57]
Hi there,

First very thanks to development of critic2. It is very convenient! I have successfully installed critic2-1.1dev version, however it did not contain the new function keyword SMOOTHRHO.  As a result,  I want to install the latest version from Github. When I install it using autoconf, after the _make_ command, it showed some error:
![1](https://user-images.githubusercontent.com/122458488/225310932-ef8ee2ea-5662-480a-a308-494f43f5d2f0.png)
and in critic2 it showed:
![3](https://user-images.githubusercontent.com/122458488/225311221-33330e67-817d-4f58-b9b3-7b460cbedece.png)
![2](https://user-images.githubusercontent.com/122458488/225311047-bdaefe47-1049-4511-9b95-fd8a924c4648.png)
I have set the environment like this:
![4](https://user-images.githubusercontent.com/122458488/225311810-b8b2726f-9bac-4031-a1c6-d2a89ceb538d.png)
 So I was wondering where went wrong? Is there problem in the complier? Hope you can help me solve the problem. It would be so much thanks!

**Comment by aoterodelaroza** [comment]
Hi @PolyuWeldingSpock : the SMOOTHRHO keyword is very recent; you need to download the github version. See the instructions [here](https://aoterodelaroza.github.io/critic2/) for using `git clone`. I strongly recommend using `cmake` instead of `configure` to build the code. You can find the instructions [in this other page](https://aoterodelaroza.github.io/critic2/installation/). At the same place, you can find how to set the `CRITIC_HOME` environment variable, which is needed for critic2 to find its files - otherwise you need to do `make install`. There was an error in the automake scripts that prevented compilation and caused your error. I've just pushed the change to the repo.

**Comment by PolyuWeldingSpock** [comment]
Hi @aoterodelaroza ! As you can see in my previous comment, I have set the `CRITIC_HOME` environment variable. Also, the `make install`  did not work. I will try to use `cmake` and hope this could work. Thank you!

**Comment by aoterodelaroza** [comment]
Sorry, you're right. `configure/make` should work with the changes I made before you pulled. Let me know.

**Comment by PolyuWeldingSpock** [comment]
Hi@[aoterodelaroza](https://github.com/aoterodelaroza) , I tried to download the latest version and build the code with `cmake`. After building, I used `make install` to install and showed error:
![1678953365708](https://user-images.githubusercontent.com/122458488/225551115-3863268b-7c02-4600-9621-70f607040033.png)
Because I was trying to install critic2 on HPC but under my personal account. Dis this mean I cannot install it without the administrator privileges?

**Comment by aoterodelaroza** [comment]
You cannot if you want to install to `/usr/local`, which is the default. To change the installation directory, use `-DCMAKE_INSTALL_PREFIX`, as instructed by the installation page in the manual. However, you seem to have the critic2 binary already built in `/home/s22117712r/critic2/build/src/critic2` so just set the `CRITIC_HOME` environment variable to `/home/s22117712r/critic2` as you did above and execute that binary directly. You do not need to install.

**Comment by PolyuWeldingSpock** [comment]
Very thank you! Problem solved. Thanks to your patient answer!

**Comment by aoterodelaroza** [comment]
No problem, thanks!
