### ISSUE TITLE
Version number question

### ISSUE THREAD

**Issue by mkhorton** [aoterodelaroza/critic2#6]
Do you have any version numbers defined in your code? What version is your 'stable' release at, is it simply 2.0?

(I'm asking because I wanted to contribute a critic2 package to the homebrew package manager to make it easier to install for mac users to install critic2, but the maintainers require a version number to be defined.)

**Comment by aoterodelaroza** [comment]
I normally use the first seven characters of the github commit, but
this is not ideal. Beyond that, there is little in the way of
versioning. The "stable" tag exists now because most Fortran compilers
do not support some features I need, and I wanted to give users who
just want some working code an option. More people seem to use critic2
now, so maybe it is time to introduce versioning tags. In the
meantime, I'd go with 2.0-stable or 2.0-development.

* Matthew Horton <notifications@github.com> [2017-08-28 11:13:48 -0700]:

**Comment by mkhorton** [comment]
Okay, that's good to know. Thank you!
