### ISSUE TITLE
QE 7.2: Voronoi charges sum roughly equal to Natoms/2

### ISSUE THREAD

**Issue by tomdemeyere** [aoterodelaroza/critic2#62]
I tried to compute Voronoi charges on a platinum cluster consisting of 353 atoms. The total population ends up summing to ~ 176.5, which is roughly half the number of atoms.

  Sum                            4.31896065E+05  1.76505353E+02 -1.06914477E-13 

I use QE 7.2 and plot_num = 9, the pseudopotential is USPP GBRV 1.4. I can provide more details if necessary.

EDIT: I just realised that this PP has a configuration:                         
                       5P  1  6.00
                       5D  2  9.50

That QE interpret as '16' valence electrons, it is very much possible that during the removal of the 'atomic densities' half an electron is then missing? In this case I can probably subtract 0.5 to every charge on Pt and get the correct answer?

**Comment by aoterodelaroza** [comment]
Sorry, I've just seen your edit. I'd consider switching to a PAW dataset just for this calculation. You have no guarantees that the extra charge won't exceed the atomic boundaries. Point 2 above is a good way of checking whether your input density makes sense or not.

**Comment by tomdemeyere** [comment]
Thank you for the answer,

1. The volume is the same yes
2. Unfortunately it is equal to 176.50535318 (half the number of Pt atoms)
3. I didn't try with older version but I just tried the same including oxygen atoms (PAW for oxygens) adsorbed on the nanoparticle and I get the same sum ~ 176.5. It might be a problem with this specific Pt PP or USPP in general. These calculations are fairly expensive, I will see if I am able to run them again with another set of PPs.

**Comment by aoterodelaroza** [comment]
I've just tried with NC, US, and PAW pseudos from the pslibrary on diamond with version 6.7MaX, and all of them seem to give a zero cell integral. It seems it could be those specific Pt pseudos.

**Comment by tomdemeyere** [comment]
I will ask on the QE mailing list about it. In any case bader charges look reasonable with these PPs, I am maybe going to stick to that instead.

Something I had a doubt about: Does VDD/HIRSHFELD charges requires PAW calculations normally?

**Comment by aoterodelaroza** [comment]
They do not. As long as you have a density that integrates to the correct number of valence electrons (or to zero if you use the deformation density), you are fine. A different question is whether the results are significantly affected by the smoothing from the pseudo, which in my experience is almost never the case. You do need PAW for the Bader charges, because in that case you need the all-electron density to determine the atomic basins, which is not a problem for VDD or HIRSHFELD. You can sort of fudge it by adding the core contribution from critic2's internal density tables, but it's better to use PAW. See: https://aoterodelaroza.github.io/critic2/examples/example_11_01_simple-integration/#c2-bader

**Comment by tomdemeyere** [comment]
Thank you for all your answers. I might think about running a final single-point changing all the PPs to PAW and using a denser grid...

You might want to let this issue open for me to post the answer of the QE forums, if you wish.

**Comment by aoterodelaroza** [comment]
sure, thanks!
