### ISSUE TITLE
Core augmentation issue for transition metals(e.g Ti) for non-PAW calculation done by Qunatum Espresso

### ISSUE THREAD

**Issue by unmesh1993** [aoterodelaroza/critic2#8]
Using Quantum Espresso (QE), I have run a non-PAW calculation to get the pseudo charge density grid file (plotnum=0 in pp.x post-processing tool of QE) for Ti. The YT integration of this charge density gives me the right number of electrons(Ti -12 as given in the pseudopotential) upon the integration. But, when I augment this pseudo-density file with the core charges taken from the critic2 database, I end up getting an incorrect number of electrons (should be 22 for Ti). But for the case of C, the total number of electrons upon augmentation is close to 6. I am attaching the Gaussian cube file along with the critic input and output and the pseudo-potential for both Ti and C. 
Please help me out with this issue.
[Ti.tar.gz](https://github.com/aoterodelaroza/critic2/files/1320559/Ti.tar.gz)
[C.tar.gz](https://github.com/aoterodelaroza/critic2/files/1320561/C.tar.gz)

**Comment by aoterodelaroza** [comment]
The augmented core density does not sum to the correct number of
electrons because a uniform grid cannot represent the very steep
density peaks at the nuclei correctly, regardless of how fine you make
it. It is the same reason why pseudopotentials are used in plane-wave
calculations. The $rhoval column is almost always what you want.

Also, note that you are core-augmenting twice: once when you write the
rhof.cube and another when you load that same cube with the core
option within the same input. Those two steps are meant to be run
separately - that way you do not need to generate a cube-augmented
cube every time you want to run YT.
